# YAML file for config.yaml
path: /Users/madisonattobra/Documents/data
train: images/train/ # directory of training images
val: images/train/ # directory of validation images

names:
  0: shell
  1: shellp
